param(
  [string]$BackendBuildDir = "backend\build"
)

$ErrorActionPreference = "Stop"
$RootDir = $PSScriptRoot

# ─── Version helpers ─────────────────────────────────────────────────────
function Get-SrcHash {
  param([string]$Dir, [string[]]$Extensions, [string[]]$Exclude = @())
  $files = Get-ChildItem -Path $Dir -Recurse -File | Where-Object {
    $ext = $_.Extension.ToLower()
    ($Extensions -contains $ext) -and ($Exclude -notcontains $_.Name)
  } | Sort-Object FullName
  if (-not $files) { return "empty" }
  $hasher = [System.Security.Cryptography.SHA256]::Create()
  $stream = New-Object System.IO.MemoryStream
  foreach ($f in $files) {
    $bytes = [System.IO.File]::ReadAllBytes($f.FullName)
    $stream.Write($bytes, 0, $bytes.Length)
  }
  $stream.Position = 0
  $hashBytes = $hasher.ComputeHash($stream)
  $stream.Close()
  return [BitConverter]::ToString($hashBytes) -replace '-', ''
}

function Read-Version {
  param([string]$File)
  if (Test-Path $File) { return (Get-Content $File -Raw).Trim() }
  return "0.0.0"
}

function Increment-Patch {
  param([string]$Ver)
  $parts = $Ver -split '\.'
  $parts[2] = [int]$parts[2] + 1
  return "$($parts[0]).$($parts[1]).$($parts[2])"
}

$script:anyChanged = $false

function Maybe-Bump {
  param([string]$VersionFile, [string]$HashFile, [string]$NewHash)
  $oldHash = ""
  if (Test-Path $HashFile) { $oldHash = (Get-Content $HashFile -Raw).Trim() }
  $currentVer = Read-Version $VersionFile
  if ($oldHash -ne $NewHash) {
    $newVer = Increment-Patch $currentVer
    Set-Content -Path $VersionFile -Value $newVer -NoNewline
    Set-Content -Path $HashFile -Value $NewHash -NoNewline
    $script:anyChanged = $true
    return $newVer
  }
  return $currentVer
}

# ─── Backend ─────────────────────────────────────────────────────────────
Write-Host "`n==> Checking backend sources" -ForegroundColor Cyan
$backendHash = Get-SrcHash "$RootDir\backend\src" @(".cc", ".h", ".cmake") @("version.h")
$backendVer = Maybe-Bump "$RootDir\backend\VERSION" "$RootDir\backend\.src_hash" $backendHash
Write-Host "  Backend version: $backendVer"
@"
#pragma once
// This file is auto-generated by build-all.ps1
#define APP_VERSION "$backendVer"
"@ | Set-Content "$RootDir\backend\src\version.h"

Write-Host "`n==> Building backend" -ForegroundColor Cyan
Push-Location "backend"
cmake -S . -B $BackendBuildDir -G "MinGW Makefiles"
cmake --build $BackendBuildDir
Pop-Location

# ─── Frontend ────────────────────────────────────────────────────────────
Write-Host "`n==> Checking frontend sources" -ForegroundColor Cyan
$frontendHash = Get-SrcHash "$RootDir\frontend\src" @(".jsx", ".js", ".css", ".html")
$frontendVer = Maybe-Bump "$RootDir\frontend\VERSION" "$RootDir\frontend\.src_hash" $frontendHash
Write-Host "  Frontend version: $frontendVer"
$pkgJson = Get-Content "$RootDir\frontend\package.json" -Raw
$pkgJson = $pkgJson -replace '"version":\s*"[^"]*"', "`"version`": `"$frontendVer`""
Set-Content "$RootDir\frontend\package.json" -Value $pkgJson -NoNewline

Write-Host "`n==> Building frontend" -ForegroundColor Cyan
Push-Location "frontend"
if (-not (Test-Path "node_modules")) { npm install }
npm run build
Pop-Location

# ─── Agent ───────────────────────────────────────────────────────────────
Write-Host "`n==> Checking agent sources" -ForegroundColor Cyan
$agentHash = Get-SrcHash "$RootDir\agent" @(".go", ".mod", ".sum")
$agentVer = Maybe-Bump "$RootDir\agent\VERSION" "$RootDir\agent\.src_hash" $agentHash
Write-Host "  Agent version: $agentVer"

Write-Host "`n==> Building EndoriumFortAgent (v$agentVer)" -ForegroundColor Cyan
Push-Location "agent"
$goPath = Get-Command go -ErrorAction SilentlyContinue
if ($goPath) {
  $ldflags = "-X main.version=$agentVer"
  $env:GOOS = "windows"
  $env:GOARCH = "amd64"
  go build -ldflags $ldflags -o endoriumfort-agent.exe .
  Write-Host "  Agent binary (Windows): agent\endoriumfort-agent.exe"
} else {
  Write-Host "  Go not found - skipping agent build"
}
Pop-Location

# ─── Global version & Git ────────────────────────────────────────────────
$globalVerFile = "$RootDir\VERSION"
$globalVer = Read-Version $globalVerFile

if ($script:anyChanged) {
  $globalVer = Increment-Patch $globalVer
  Set-Content -Path $globalVerFile -Value $globalVer -NoNewline
  Write-Host "  Global version bumped -> v$globalVer"

  # Git commit & tag
  $gitDir = Get-Command git -ErrorAction SilentlyContinue
  if ($gitDir) {
    Push-Location $RootDir
    git add -A
    git commit -m "build: v${globalVer} — backend v${backendVer}, frontend v${frontendVer}, agent v${agentVer}" --allow-empty 2>$null
    git tag -f "v${globalVer}" -m "Release v${globalVer}" 2>$null
    Write-Host "  Commit: build v${globalVer}"
    Write-Host "  Tag:    v${globalVer}"
    Pop-Location
  }
} else {
  Write-Host "  No source changes — global version stays at v$globalVer"
}

# ─── Summary ─────────────────────────────────────────────────────────────
Write-Host "`n==> Build completed" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Global:   v$globalVer"
Write-Host "  Backend:  v$backendVer"
Write-Host "  Frontend: v$frontendVer"
Write-Host "  Agent:    v$agentVer"
Write-Host ""
