#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

info() {
  printf "\n\033[1;36m==> %s\033[0m\n" "$1"
}

# ─── Version helpers ─────────────────────────────────────────────────────
# Compute a hash of source files in a directory (excluding build artifacts)
src_hash() {
  local dir="$1"
  shift
  # Find source files matching patterns, hash their contents
  find "$dir" "$@" -type f | LC_ALL=C sort | xargs cat 2>/dev/null | sha256sum | cut -d' ' -f1
}

# Read current version from a VERSION file (defaults to 0.0.0)
read_version() {
  local file="$1"
  if [[ -f "$file" ]]; then
    cat "$file" | tr -d '[:space:]'
  else
    echo "0.0.0"
  fi
}

# Increment patch version: 1.2.3 -> 1.2.4
increment_patch() {
  local ver="$1"
  local major minor patch
  IFS='.' read -r major minor patch <<< "$ver"
  patch=$((patch + 1))
  echo "${major}.${minor}.${patch}"
}

# Track whether any component changed during this build
CHANGE_FLAG="$ROOT_DIR/.build_changed"
rm -f "$CHANGE_FLAG"

# Check if sources changed; if so, increment version and return new version.
# Usage: maybe_bump <VERSION_file> <hash_cache_file> <new_hash>
maybe_bump() {
  local version_file="$1"
  local hash_file="$2"
  local new_hash="$3"

  local old_hash=""
  if [[ -f "$hash_file" ]]; then
    old_hash="$(cat "$hash_file" | tr -d '[:space:]')"
  fi

  local current_ver
  current_ver="$(read_version "$version_file")"

  if [[ "$old_hash" != "$new_hash" ]]; then
    local new_ver
    new_ver="$(increment_patch "$current_ver")"
    echo "$new_ver" > "$version_file"
    echo "$new_hash" > "$hash_file"
    touch "$CHANGE_FLAG"
    echo "$new_ver"
  else
    echo "$current_ver"
  fi
}

# ─── Backend ─────────────────────────────────────────────────────────────
info "Checking backend sources"
BACKEND_HASH=$(find "$ROOT_DIR/backend/src" -type f \( -name '*.cc' -o -name '*.h' -o -name '*.cmake' \) ! -name 'version.h' | LC_ALL=C sort | xargs cat 2>/dev/null | sha256sum | cut -d' ' -f1)
BACKEND_VER=$(maybe_bump "$ROOT_DIR/backend/VERSION" "$ROOT_DIR/backend/.src_hash" "$BACKEND_HASH")
echo "  Backend version: $BACKEND_VER"

# Regenerate version.h
cat > "$ROOT_DIR/backend/src/version.h" <<EOF
#pragma once
// This file is auto-generated by build-all.sh
#define APP_VERSION "$BACKEND_VER"
EOF

info "Building backend"
cmake -S "$ROOT_DIR/backend" -B "$ROOT_DIR/backend/build"
cmake --build "$ROOT_DIR/backend/build"

# ─── Frontend ────────────────────────────────────────────────────────────
info "Checking frontend sources"
FRONTEND_HASH=$(src_hash "$ROOT_DIR/frontend/src" -name '*.jsx' -o -name '*.js' -o -name '*.css' -o -name '*.html')
FRONTEND_VER=$(maybe_bump "$ROOT_DIR/frontend/VERSION" "$ROOT_DIR/frontend/.src_hash" "$FRONTEND_HASH")
echo "  Frontend version: $FRONTEND_VER"

# Update package.json version in place
sed -i.bak "s/\"version\": \"[^\"]*\"/\"version\": \"$FRONTEND_VER\"/" "$ROOT_DIR/frontend/package.json"
rm -f "$ROOT_DIR/frontend/package.json.bak"

info "Building frontend"
cd "$ROOT_DIR/frontend"
NPM_PATH="$(command -v npm || true)"
if [[ -z "$NPM_PATH" ]]; then
  echo "npm not found. Install Node.js/npm to build the frontend." >&2
  exit 1
fi
# WSL-specific check: avoid Windows npm via /mnt/
if [[ "$NPM_PATH" == /mnt/* ]]; then
  echo "Detected Windows npm at $NPM_PATH. Use the Linux npm in WSL to avoid UNC path issues." >&2
  echo "Try: sudo apt update && sudo apt install nodejs npm" >&2
  exit 1
fi
if [[ ! -d node_modules ]]; then
  npm install
fi
npm run build

# ─── Agent ───────────────────────────────────────────────────────────────
info "Checking agent sources"
AGENT_HASH=$(src_hash "$ROOT_DIR/agent" -name '*.go' -o -name 'go.mod' -o -name 'go.sum')
AGENT_VER=$(maybe_bump "$ROOT_DIR/agent/VERSION" "$ROOT_DIR/agent/.src_hash" "$AGENT_HASH")
echo "  Agent version: $AGENT_VER"

info "Building EndoriumFortAgent (v$AGENT_VER)"
cd "$ROOT_DIR/agent"
GO_PATH="$(command -v go || true)"
if [[ -z "$GO_PATH" ]]; then
  echo "go not found. Install Go to build the agent." >&2
  echo "Agent build skipped."
else
  LDFLAGS="-X main.version=$AGENT_VER"

  # Detect host architecture
  HOST_ARCH="amd64"
  case "$(uname -m)" in
    arm64|aarch64) HOST_ARCH="arm64" ;;
  esac

  # Native binary (Linux or macOS)
  HOST_OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
  case "$HOST_OS" in
    darwin) HOST_OS="darwin" ;;
    *)      HOST_OS="linux" ;;
  esac
  GOOS="$HOST_OS" GOARCH="$HOST_ARCH" go build -ldflags "$LDFLAGS" -o endoriumfort-agent .
  echo "  Agent binary (native $HOST_OS/$HOST_ARCH): $ROOT_DIR/agent/endoriumfort-agent"

  # Cross-compile: Linux amd64 (skip if already native)
  if [[ "$HOST_OS" != "linux" || "$HOST_ARCH" != "amd64" ]]; then
    GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS" -o endoriumfort-agent-linux-amd64 .
    echo "  Agent binary (Linux amd64): $ROOT_DIR/agent/endoriumfort-agent-linux-amd64"
  fi

  # Cross-compile: Windows .exe
  GOOS=windows GOARCH=amd64 go build -ldflags "$LDFLAGS" -o endoriumfort-agent.exe .
  echo "  Agent binary (Windows amd64): $ROOT_DIR/agent/endoriumfort-agent.exe"

  # Cross-compile: macOS (skip if already native)
  if [[ "$HOST_OS" != "darwin" ]]; then
    GOOS=darwin GOARCH=arm64 go build -ldflags "$LDFLAGS" -o endoriumfort-agent-darwin-arm64 .
    echo "  Agent binary (macOS arm64): $ROOT_DIR/agent/endoriumfort-agent-darwin-arm64"
  fi
fi

# ─── Global version & Git ────────────────────────────────────────────────
GLOBAL_VER_FILE="$ROOT_DIR/VERSION"
GLOBAL_VER=$(read_version "$GLOBAL_VER_FILE")

if [[ -f "$CHANGE_FLAG" ]]; then
  GLOBAL_VER=$(increment_patch "$GLOBAL_VER")
  echo "$GLOBAL_VER" > "$GLOBAL_VER_FILE"
  echo "  Global version bumped → v$GLOBAL_VER"

  # Git commit & tag (only if inside a git repo)
  if git -C "$ROOT_DIR" rev-parse --git-dir >/dev/null 2>&1; then
    info "Git commit & tag"
    cd "$ROOT_DIR"
    git add -A
    git commit -m "build: v${GLOBAL_VER} — backend v${BACKEND_VER}, frontend v${FRONTEND_VER}, agent v${AGENT_VER}" \
      --allow-empty 2>/dev/null || true
    git tag -f "v${GLOBAL_VER}" -m "Release v${GLOBAL_VER}" 2>/dev/null || true
    echo "  Commit: build v${GLOBAL_VER}"
    echo "  Tag:    v${GLOBAL_VER}"
  fi
  rm -f "$CHANGE_FLAG"
else
  echo "  No source changes — global version stays at v$GLOBAL_VER"
fi

# ─── Summary ─────────────────────────────────────────────────────────────
info "Build completed"
echo
echo "  Global:   v$GLOBAL_VER"
echo "  Backend:  v$BACKEND_VER"
echo "  Frontend: v$FRONTEND_VER"
echo "  Agent:    v$AGENT_VER"
echo
